language: php

php:
  # php versions to check
  - 7.1

install:
  # install composer dependencies
  - composer install --prefer-source

script:
  # run tests
  - vendor/bin/phpunit

# do not send success notifications, they have no value
notifications:
  email:
    on_success: never
